### PR TITLE
Set up Travis & CodeCov

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
This is our standard setup already used by many packages in this organisation. With its help, you will be able to monitor the status of the tests of your package and code coverage.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
All seem to work - ready for "rebase and merge".

**Comment by laurentbartholdi** [comment]
Hi Alex:
In principle, I'm all OK -- but what is the "matrix" and "clang" stuff appearing in the .yml file?

**Comment by olexandr-konovalov** [comment]
This allows to run tests in several different settings, e.g. with different compilers, 32/64-bit builds etc. This is our standard setup, and it is useful even for packages that do not have binaries, since they may depend on other compiled code.

**Comment by olexandr-konovalov** [comment]
@laurentbartholdi I've rebased this to check that tests pass with the latest changes. Will you be happy to merge this now?

**Pull request merged**
